
INSERT INTO `bdtiendamusica`.`artistas` (`nombre`, `nacionalidad`) VALUES 
('The Beatles', 'Reino Unido'),
('Elvis Presley', 'Estados Unidos'),
('Michael Jackson', 'Estados Unidos'),
('Madonna', 'Estados Unidos'),
('Queen', 'Reino Unido'),
('The Rolling Stones', 'Reino Unido'),
('Led Zeppelin', 'Reino Unido'),
('Pink Floyd', 'Reino Unido'),
('AC/DC', 'Australia'),
('David Bowie', 'Reino Unido'),
('U2', 'Irlanda'),
('The Beach Boys', 'Estados Unidos'),
('Bob Dylan', 'Estados Unidos'),
('Bruce Springsteen', 'Estados Unidos'),
('The Who', 'Reino Unido'),
('Nirvana', 'Estados Unidos'),
('The Police', 'Reino Unido'),
('The Doors', 'Estados Unidos'),
('The Eagles', 'Estados Unidos'),
('Fleetwood Mac', 'Reino Unido'),
('Aerosmith', 'Estados Unidos'),
('Guns N\' Roses', 'Estados Unidos'),
('Red Hot Chili Peppers', 'Estados Unidos'),
('The Clash', 'Reino Unido'),
('Metallica', 'Estados Unidos'),
('Bon Jovi', 'Estados Unidos'),
('Pearl Jam', 'Estados Unidos'),
('Green Day', 'Estados Unidos'),
('R.E.M.', 'Estados Unidos'),
('The Cure', 'Reino Unido'),
('Oasis', 'Reino Unido'),
('Blur', 'Reino Unido'),
('Radiohead', 'Reino Unido'),
('Coldplay', 'Reino Unido'),
('The Smiths', 'Reino Unido'),
('ABBA', 'Suecia'),
('Bee Gees', 'Reino Unido'),
('Eagles', 'Estados Unidos'),
('Santana', 'Estados Unidos'),
('Elton John', 'Reino Unido'),
('Billy Joel', 'Estados Unidos'),
('Prince', 'Estados Unidos'),
('Rihanna', 'Barbados'),
('Beyoncé', 'Estados Unidos'),
('Adele', 'Reino Unido'),
('Taylor Swift', 'Estados Unidos'),
('Justin Bieber', 'Canadá'),
('Ed Sheeran', 'Reino Unido'),
('Bruno Mars', 'Estados Unidos'),
('Katy Perry', 'Estados Unidos'),
('Lady Gaga', 'Estados Unidos'),
('Shakira', 'Colombia'),
('Luis Miguel', 'México'),
('Juanes', 'Colombia'),
('Maná', 'México'),
('Café Tacvba', 'México'),
('Soda Stereo', 'Argentina'),
('Charly García', 'Argentina'),
('Fito Páez', 'Argentina'),
('Caifanes', 'México'),
('Los Fabulosos Cadillacs', 'Argentina'),
('Los Auténticos Decadentes', 'Argentina'),
('La Oreja de Van Gogh', 'España'),
('Mecano', 'España'),
('Alejandro Sanz', 'España'),
('Enrique Iglesias', 'España'),
('Pablo Alborán', 'España'),
('Jarabe de Palo', 'España'),
('Héroes del Silencio', 'España');