INSERT INTO `bdtiendamusica`.`generos` (`nombre`) VALUES
('Rock'),
('Pop'),
('Blues'),
('Reggae'),
('Hip Hop'),
('R&B'),
('Country'),
('Classical'),
('Electronic'),
('Metal'),
('Punk'),
('Soul'),
('Funk'),
('Disco'),
('Gospel'),
('Latin'),
('Folk'),
('Alternative Rock'),
('Indie Rock'),
('Hard Rock'),
('Grunge'),
('New Wave'),
('Synthpop');